PROG1 = Final_Knapsack.c

FILE1 = knapsack

PROG2 = ui_curses.c

PROG3 = Final_Knapsack2.c

FLAG1 = lncurses

CC = gcc

CFAGS = -lncurses.

make:
	$(CC) -o $(FILE1) $(PROG1) $(PROG2) -$(FLAG1)&& ./$(FILE1)
